services:
  - type: web
    name: api-de-estoque
    env: python
    pythonVersion: 3.12.10
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.principal:aplicacao --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: TEST_API_KEY
        sync: false
      - key: CORS_ORIGINS
        sync: false